### ISSUE TITLE
Runfile 1.0 Roadmap

### ISSUE THREAD

**Issue by egoist** [runfile/runfile#26]
- [ ] A Node.js API
- [ ] Separated task files support
- [ ] More elegant grammer
- [ ] Support other default file names, like `Runfie.js` `runfile.js` or custom file `--config run.config.js`
